[behave]
# test features path
paths = features
# if false show terminal output (print statements, errors)
# if true hide terminal output 
stdout_capture = false
stderr_capture = false
log_capture = false

# Default environment if -D env=xxx or TEST_ENV is not passed
userdata.env = dev

# Default report format (pretty locally, allure in CI)
format   = pretty
show_timings = true
